apiVersion: v1
kind: ConfigMap
metadata:
  name: apipostech-config-agendamento
data:
  ASPNETCORE_ENVIRONMENT: "Development"  
  RedisSettings__ConnectionString: "localhost:6379"
  RedisSettings__InstanceName: "Agendamento_"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apipostech-deployment-agendamento
  labels:
    app: apipostech-agendamento
spec:
  replicas: 2  # Número de réplicas desejadas
  selector:
    matchLabels:
      app: apipostech-agendamento  # Seleciona os pods com esta label
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: apipostech-agendamento  # Label aplicada aos pods
    spec:
      containers:
      - name: apipostech-agendamento
        image: postech.hackathon.agenda:1.1
        ports:
        - containerPort: 8080  
        envFrom:        
        - configMapRef:
            name: database-shared-config-agendamento
        - configMapRef:
            name: apipostech-config-agendamento
        - configMapRef:
            name: jwt-settings-config

--- 
apiVersion: v1
kind: Service
metadata:
  name: apipostech-agendamento-service
  labels:
    app: apipostech-agendamento
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8044
      targetPort: 8081
      protocol: TCP
      name: https
  selector:
    app: apipostech-agendamento
