apiVersion: v1
kind: ConfigMap
metadata:
  name: apipostech-config-pessoa
data:
  ASPNETCORE_ENVIRONMENT: "Development"  
  RedisSettings__ConnectionString: "localhost:6379"
  RedisSettings__InstanceName: "GestorCadastro_"
---
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apipostech-deployment-pessoa
  labels:
    app: apipostech-pessoa
spec:
  replicas: 2  # Número de réplicas desejadas
  selector:
    matchLabels:
      app: apipostech-pessoa  # Seleciona os pods com esta label
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: apipostech-pessoa  # Label aplicada aos pods
    spec:
      containers:
      - name: apipostech-pessoa
        image: postech.hackathon.gestorpessoa:1.0
        ports:
        - containerPort: 8080  
        envFrom:        
        - configMapRef:
            name: apipostech-config
        - configMapRef:
            name: database-shared-config-pessoa
        - configMapRef:
            name: jwt-settings-config
--- 
apiVersion: v1
kind: Service
metadata:
  name: apipostech-service-pessoa
  labels:
    app: apipostech-pessoa
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8043
      targetPort: 8081
      protocol: TCP
      name: https
  selector:
    app: apipostech-pessoa
